# Generated by Django 6.0.1 on 2026-01-30 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Мышечная группа',
                'verbose_name_plural': 'Мышечные группы',
            },
        ),
        migrations.CreateModel(
            name='RealSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время тренировки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий по тренировке')),
            ],
            options={
                'verbose_name': 'Реальная сессия',
                'verbose_name_plural': 'Реальные сессии',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(verbose_name='Описание техники')),
                ('muscles', models.ManyToManyField(related_name='exercises', to='workout.musclegroup', verbose_name='Мышечная группа')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_reps', models.IntegerField(verbose_name='Повторения')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Вес снаряда(кг)')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workout.exercise', verbose_name='Название упражнения')),
                ('session_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workout.realsession', verbose_name='Сессия')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название тренировочного плана')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_templates', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Тренировочный шаблон',
                'verbose_name_plural': 'Тренировочные шаблоны',
            },
        ),
        migrations.AddField(
            model_name='realsession',
            name='template_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_sessions', to='workout.workouttemplate', verbose_name='Шаблон тренировки'),
        ),
        migrations.CreateModel(
            name='ExerciseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_sets', models.IntegerField(verbose_name='Количество подходов')),
                ('reps', models.IntegerField(verbose_name='Количество повторений')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_templates', to='workout.exercise', verbose_name='Название упражнения')),
                ('workout_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_templates', to='workout.workouttemplate', verbose_name='Тренировочный шаблон')),
            ],
            options={
                'verbose_name': 'Упражнение в тренировочном плане',
                'verbose_name_plural': 'Упражнения в тренировочном плане',
            },
        ),
    ]
