# Generated by Django 6.0.1 on 2026-02-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fat_percent',
            field=models.DecimalField(decimal_places=1, default=23, max_digits=4, verbose_name='Процент подкожного жира(%)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='height',
            field=models.IntegerField(default=188, verbose_name='Рост(см)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='weight_body',
            field=models.DecimalField(decimal_places=1, default=95, max_digits=5, verbose_name='Вес(кг)'),
        ),
    ]
